IMDB Dataset of 50K Movie Reviews

In [4]:
import pandas as pd

In [5]:
data = "../IMDB Dataset.csv"
df = pd.read_csv(data)
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df = df.sample(frac=0.1, random_state=1)
df.shape

(500, 2)

Converting to lower

In [8]:
df['review'] = df['review'].str.lower()
df.head()

                                                  review sentiment
21842  bela lugosi as creepy insane scientist who use...  negative
48842  i should have trusted my instincts better: no ...  negative
37824  there is no such a thing as perfect murder.lie...  positive
21667  critics claim that this film is one of the wor...  positive
49802  the brothers quay are directors, judging by co...  negative

Removing HTML tags with regular expressions

In [9]:
import re
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

In [13]:
text  = "<html><head><title>A Title</title></head><body><h1>Header</h1><p>This is a paragraph.</p></body></html>"
remove_html_tags(text)

'A TitleHeaderThis is a paragraph.'